# Generated by Django 4.0.4 on 2022-05-10 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, verbose_name='student')),
                ('report_type', models.CharField(max_length=255, verbose_name='report type')),
                ('type_others', models.CharField(blank=True, max_length=255, null=True, verbose_name='type others')),
                ('evaluator_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='evaluator')),
                ('message', models.TextField(verbose_name='message')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='details')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket-attachment/', verbose_name='attachment')),
                ('status', models.CharField(default=False, max_length=20, verbose_name='status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
            ],
            options={
                'db_table': 'incident',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_notif', to='base.incident')),
            ],
            options={
                'db_table': 'notification',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user')),
                ('message', models.TextField(verbose_name='message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket-attachment/', verbose_name='attachment')),
                ('is_solution', models.BooleanField(default=False)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='base.incident')),
            ],
            options={
                'db_table': 'incident_follow_up',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
