# Generated by Django 4.0.4 on 2022-05-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('attendee', models.CharField(max_length=255, verbose_name='attendees')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='event-attachment/', verbose_name='attachment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=255, verbose_name='report type')),
                ('type_others', models.CharField(max_length=255, verbose_name='type others')),
                ('message', models.TextField(verbose_name='message')),
                ('details', models.CharField(max_length=255, verbose_name='details')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket-attachment/', verbose_name='attachment')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('news_date', models.DateTimeField(verbose_name='news date')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='news-attachment/', verbose_name='attachment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'news',
            },
        ),
    ]
