# Generated by Django 4.0.4 on 2022-05-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='evaluator',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='followup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='incident',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='notification',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
