# Generated by Django 4.0.4 on 2022-05-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(default='Open', max_length=20, verbose_name='status'),
        ),
    ]
