# Generated by Django 4.0.4 on 2022-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_student_permanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='residential_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='residential address'),
        ),
    ]
