# Generated by Django 4.0.4 on 2022-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_evaluator_residential_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='details',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='message',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='type_others',
        ),
        migrations.AddField(
            model_name='incident',
            name='report_details',
            field=models.TextField(blank=True, null=True, verbose_name='report details'),
        ),
        migrations.AddField(
            model_name='incident',
            name='report_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='report title'),
        ),
        migrations.AddField(
            model_name='incident',
            name='subject_add',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject_add'),
        ),
    ]
