# Generated by Django 4.0.4 on 2022-05-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_incident_details_remove_incident_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='subject_add',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject add'),
        ),
    ]
