# Generated by Django 4.0.4 on 2022-05-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_followup_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardincident',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
    ]
